### PR TITLE
Welcome the new grid!

### PR DESCRIPTION
**Pull request by loup-brun**
Same as the previous pull request, but with fix (include 100% rather than 1% on line 52).

### CODE REVIEW

**Comment by matthewsimo** [comment]
I like this approach, I was manually creating the percentages rather than programmatically because I don't trust the sass compiler. But, I think flexibility gained outweighs my paranoia. Let me see how this runs with common sizes, ( 6, 9, 12, 16, 24 ) and verify that the columns are being rendered properly and not breaking rows and if everything looks good I'll merge in. Stay tuned. Thanks for spending time adding this feature! :+1:

**Comment by loup-brun** [comment]
I can submit you another project where I integrate the flexbox gris into a
'regular' fluid grid (based on floats) that I used in one of my previous
projects. That way, browsers that support flexbox (and more importantly
flex-wrap) get flex, while other vrowsers still get columns.

**Comment by matthewsimo** [comment]
Yea, share the link, I'd be interested in looking it over. I'll do some thinking on if it _makes sense_ to incorporate a non-flex fallback into the scss-flex-grid.

**Comment by loup-brun** [comment]
Here's a big one! I renamed the project to *Reflex.css* (just to give it a name).

Your demo page is full integrated with the new code I am proposing. I think this is a good shot.

You can view the demo [here](http://loup-brun.github.io/reflex.css/demo/) (it's basically the same, with some alterations).

**Next up** - a cross-browser grid, using flexbox as an enhancement.

**Comment by loup-brun** [comment]
Here we are! This is a super grid that has `flex` as an enhancement (modernizr adds a feature detection class that enables flexbox - all the flex properties take effect _ONLY_ if `display: flex` is specified).

So, you can check out the [demo page](http://loup-brun.github.io/reflex.css/demo/no-flex.html) and the [no-flex page](http://loup-brun.github.io/reflex.css/demo/index.html) (pretty much yours, but with the new code in).

How neat does that look like? :smiley:

**Comment by matthewsimo** [comment]
Thanks for your contributions, I'm excited for the work you've put in and hope you continue to maintain your fork and the features you've added that I decided after long thought weren't a great fit for this project.

**Comment by loup-brun** [comment]
All cool man. I got a little excited adding features and structure, but you're good keeping this project simple (and it's yours after all). Had fun though :smiley:

**Pull request closed without merging**
